name: Test with PR root

on:
  workflow_dispatch:
  pull_request:

permissions: {}

env:
  TRUST_CONFIG: ./trust_config.json
  IDENTITY: ${{ github.server_url }}/${{ github.workflow_ref }}

jobs:
    trust-config:
      outputs:
        trust-config-artifact-id: ${{ steps.upload.outputs.artifact-id }}
      permissions:
        contents: read
      runs-on: ubuntu-latest
      env:
        SIGNING_CONFIG: ./targets/signing_config.json
        TRUSTED_ROOT: ./targets/trusted_root.json
      steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        - name: create config files
          env:
            MEDIA_TYPE: application/vnd.dev.sigstore.clienttrustconfig.v0.1+json
          run: |
            jq -n '{trustedRoot: input, signingConfig: input}' ${{ env.TRUSTED_ROOT }} ${{ env.SIGNING_CONFIG }} | jq '.+ {"mediaType": "${{ env.MEDIA_TYPE }}"}' > ${{ env.TRUST_CONFIG }}
        - id: upload
          uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
          with:
            name: trust-config-files
            if-no-files-found: error
            path: |
              ${{ env.SIGNING_CONFIG }}
              ${{ env.TRUSTED_ROOT }}
              ${{ env.TRUST_CONFIG }}


    sigstore-python:
      needs: trust-config
      permissions:
        id-token: write # For signing with the GitHub workflow identity
        contents: read
      runs-on: ubuntu-latest
      env:
        TRUST_CONFIG: ./trust_config.json
        IDENTITY: ${{ github.server_url }}/${{ github.workflow_ref }}
      steps:
        - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
          with:
            artifact-ids: ${{ needs.trust-config.outputs.trust-config-artifact-id }}
        - run: ls -lah
        - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        - run: pip install sigstore
        - name: sign and verify
          env:
            ARTIFACT: ./README.md
          run: |
            echo "hi" > ${{ env.ARTIFACT }}
            # sign, then verify using this workflows oidc identity
            python -m sigstore --trust-config ${{ env.TRUST_CONFIG }} sign --bundle artifact.sigstore.json ${{ env.ARTIFACT }} -v
            python -m sigstore --trust-config ${{ env.TRUST_CONFIG }} verify github --cert-identity ${{ env.IDENTITY }} --bundle artifact.sigstore.json ${{ env.ARTIFACT }} -v
