name: Test with PR root

on:
  workflow_dispatch:
  pull_request:

permissions: {}

jobs:
    sigstore-python:
      permissions:
        id-token: write # For signing with the GitHub workflow identity
        contents: read
      runs-on: ubuntu-latest
      env:
        TRUST_CONFIG: ./trust_config.json
        IDENTITY: ${{ github.server_url }}/${{ github.workflow_ref }}
      steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        - run: pip install sigstore
        - name: build trust_config
          env:
            MEDIA_TYPE: application/vnd.dev.sigstore.clienttrustconfig.v0.1+json
            SIGNING_CONFIG: ./targets/signing_config.json
            TRUSTED_ROOT: ./targets/trusted_root.json
          run: |
            jq -n '{trustedRoot: input, signingConfig: input}' ${{ env.TRUSTED_ROOT }} ${{ env.SIGNING_CONFIG }} | jq '.+ {"mediaType": "${{ env.MEDIA_TYPE }}"}' > ${{ env.TRUST_CONFIG }}
        - name: sign and verify
          env:
            ARTIFACT: ./README.md
          run: |
            touch artifact
            # sign, then verify using this workflows oidc identity
            python -m sigstore --trust-config ${{ env.TRUST_CONFIG }} sign --bundle artifact.sigstore.json ${{ env.ARTIFACT }} -v
            python -m sigstore --trust-config ${{ env.TRUST_CONFIG }} verify github --cert-identity ${{ env.IDENTITY }} --bundle artifact.sigstore.json ${{ env.ARTIFACT }} -v
